
Numpy is a library for the Python programming language.  It brings the computational<br>
power of languages like C and Fortan to Python.  It includes support for large multi-demensional<br>
arrays and matrices, along with a large collection of high-level mathematical functions to<br>
operate on these arrays.<br>

In [1]:
# import the library
import numpy as np

<h2>Creating Numpy Arrays</h2>
We can create a numpy array as follows:<br>
<code>
arr = np.array([1])
print(arr)
print(type(arr))
</code><br>
Here we create a one dimensional array better known as a point like<br>
on a number line<br>

In [4]:
arr = np.array([1])
print(arr)
print(type(arr))

[1]
<class 'numpy.ndarray'>


Notice that the object is not a list but a new data structure.<br>
What will happen if we pass in an empty list to our Numpy array?<br>
<code>
arr = np.array([])
print(arr)
print(type(arr))
</code>
<br>
It will create an empty ndarray

In [5]:
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


<h2>Adding a value to a ndarray</h2>
We can add values to a numpy array using the append command.<br>
However, we need to access a numpy method for append not a python one.<br>
Type the following:<br>
<code>
arr = np.array([])
np.append(arr,2)
print(arr)
</code><br>
When we execute our code we notice that the array arr is empty.  What happened?<br>
When we use the append it adds our changes to a copy of array.  We need to either<br>
overwite the variable we used in the original assignment or create a new variable name<br>

In [12]:
arr = np.array([])
np.append(arr,2)
print(arr)  # Still Blank

[]


Type the following instead:<br>
<code>
arr = np.array([])
arr = np.append(arr,2)
print(arr)
</code>

In [13]:
arr = np.array([])
arr = np.append(arr,2)
print(arr)

[2.]


Now that we have added 1 value to our ndarray.  Let's examine its<br>
data type and its size.<br>
Type the following:<br>
<code>
arr = np.array([])
arr = np.append(arr,2)
print(arr)
print(arr.dtype)
print(arr.size)
</code><br>
When we appended the value to the ndarray we added what looked like an integer.<br>
The size returned a tople which represent the row size of 1 and no column dimension<br>
Let's look at the data types we can add after a brief exercise<br>

In [19]:
arr = np.array([])
arr = np.append(arr,2)
print(arr)
print(arr.dtype)
print(arr.size)

[2.]
float64
1
(1,)


<h2>Exercise</h2>
Create a numpy array , based on your limited knowlenge, of the number 1 through 10.<br>

<h4>solution</h4>

In [21]:
numbers = range(1,11)
arr = np.array(numbers)
print(arr)
print(arr.dtype)
print(arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
int32
10


<h2>Exercise</h2>
Create a numpy array of the inverse of all numbers from 1 through 10<br>

<h4>Solution<h4>

In [22]:
arr = np.array([1/x for x in range(1,11)])
print(arr)
print(arr.dtype)
print(arr.size)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1       ]
float64
10


<h4>Numpy.arange()</h4>
There is a faster more effient way to create sequences in numpy through the use<br>
of the built in arange method.<br>
<code>
arr = np.arange(10)
print(arr)
</code>

In [23]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


The arrange works like the python range. 
Type the following:<br>
<code>
arr = np.arange(1,11)
print(arr)
</code><br>
We passed in 2 parameters, a start and stop

In [24]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


What about the optional 3rd parameter in python.<br>
The step parameter?<br>
Type the following<br>
<code>
arr = np.arange(1,11,2)
print(arr)
</code>

In [26]:
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


Now that we have element in our ndarray, how do access individual elements?<br>
We can use indexing to access the individual elements.<br>
Type:<br>
<code>
arr = np.arange(1,11,2)
print(arr)
print(arr[1])    # Get the index 1 item
<code>

In [27]:
arr = np.arange(1,11,2)
print(arr)
print(arr[1])

[1 3 5 7 9]
3


<h2>Exercise</h2>
Create a numpy array that contains the even numbers from 10 to 40 that<br>
are not divisible by 5.

<h4>Solution<h4>

In [29]:
arr = np.array([x for x in range(10,41) if x % 2 == 0 and not x % 5 == 0])
print(arr)

[12 14 16 18 22 24 26 28 32 34 36 38]


<h2>Numpy Data Types</h2>
We noted when we appended the value 2 to the empty array that it automatically<br>
converted it to a Float64 data type.  To cast a value we can do the following:<br>
Type:<br>
<code>
x = np.int_(1.0)
print(x,type(x))
</code><br>
or<br>
<code>
arr = np.array([2,3], dtype=np.int8)
print(arr)
print(arr.dtype)
print(arr)
</code>

In [38]:
x = np.int_(1.0)
print(x,type(x))
print('='*32)
arr = np.array([2,3], dtype=np.int8)
print(arr)
print(arr.dtype)

1 <class 'numpy.int32'>
[2 3]
int8


<h2>Data types can be used as functions</h2>
If you noticed above we cast the integer using this<br>
line:<br>
<code>
x = np.int_(1.0)
print(x,type(x))
print('='*32)

x = np.float32(range(30,50,3))
print(x,type(x))
print('='*32)

x = np.array([1, 2, 3], dtype='f')
print(x)
print(type(x))
</code>

In [41]:
x = np.int_(1.0)
print(x,type(x))
print('='*32)

x = np.float32(range(30,50,3))
print(x,type(x))
print('='*32)

x = np.array([1, 2, 3], dtype='f')
print(x)
print(type(x))

1 <class 'numpy.int32'>
[30. 33. 36. 39. 42. 45. 48.] <class 'numpy.ndarray'>
[1. 2. 3.]
<class 'numpy.ndarray'>


<h4>Casting with astype()</h4>
We can convert all values in a numpy array with one function.<br>
Type:<br>
<code>
x = np.arange(11,40,5)
print(type(x))
print(x.dtype)
x = x.astype(np.int16)
print(x.dtype)
</code>
<br>
NOTE: Make sure you use the np.int8 or other type with the prefix

In [52]:
x = np.arange(11,40,5)
print(type(x))
print(x.dtype)
x = x.astype(np.int16)
print(x.dtype)

<class 'numpy.ndarray'>
int32
int16


<h2>sum, sort, round, prod, max, mean, min</h2>

In [ ]:
# We can add up the values in a numpy array
x = np.arange(11,40,5)
print(np.sum(x))  # DO NOT TYPE x.sum()

x = [10, 5, 9, 22, -7, 3]
arr = np.array(x, dtype=np.int32)
print(arr)   
print(np.sort(arr)) # Sort the values

x = np.array([2,2,3,4], dtype=np.int32)
y = np.prod(x)      # multiply each value by itself
print(y)

x = [10, 5, 9, 22, -7, 3]
print(np.max(x))    # Get the max value

x = [10, 5, 9, 22, -7, 3]
print(np.mean(x))   # Get the mean

x = [10, 5, 9, 22, -7, 3]
print(np.min(x))    # Get the mean


In [66]:
x = np.arange(11,40,5)
print(np.sum(x))  # DO NOT TYPE x.sum()

x = [10, 5, 9, 22, -7, 3]
arr = np.array(x, dtype=np.int32)
print(arr)   
print(np.sort(arr)) # Sort the values

x = np.array([2,2,3,4], dtype=np.int32)
y = np.prod(x)      # multiply each value by itself
print(y)

x = [10, 5, 9, 22, -7, 3]
print(np.max(x))    # Get the max value

x = [10, 5, 9, 22, -7, 3]
print(np.mean(x))   # Get the mean

x = [10, 5, 9, 22, -7, 3]
print(np.min(x))    # Get the mean

141
[10  5  9 22 -7  3]
[-7  3  5  9 10 22]
48
22
7.0
-7


<h2>Iterating over a numpy object</h2>
We can iterate over a numby object using the index of the object.<br>
<code>
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
for i in x:
    print(i, type(i))
</code>

In [73]:
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
for i in x:
    print(i, type(i))

10 <class 'numpy.int16'>
5 <class 'numpy.int16'>
9 <class 'numpy.int16'>
22 <class 'numpy.int16'>
-7 <class 'numpy.int16'>
3 <class 'numpy.int16'>


We can use the index of the numpy object to change its values in the index.<br>
<code>
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
x[0] = x[0] * 2
print(x)
</code>

In [74]:
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
x[0] = x[0] * 2
print(x)

[20  5  9 22 -7  3]



We use numpy for the speed an efficiency of its numerical calculations.
<br>
NOTE: ALL OF THE DATA IS OF 1 TYPE, THERFORE THE COMPUTATIONAL SPEED IS FASTER
<br>
Type:<br>
<code>
x = [10, 5, 9, 22, -7, 3]
x = np.array(x) * 2
print(x)
</code><br>
We have applied an operator to the entire object without iterating over the object!!!

In [75]:
x = [10, 5, 9, 22, -7, 3]
x = np.array(x) * 2
print(x)

[ 20  10  18  44 -14   6]


<h2>Exercise</h2>
Caclulate the max, min, range, mean, and standard deviation using <br>
your limited knowledga of numpy using the following data set:<br>
<code>
[68.0, 90.0, 69.0, 86.0, 78.0, 97.0, 95.0, 83.0, 84.0, 74.0, 84.0, 71.0, 79.0, 
 82.0, 79.0, 69.0, 99.0, 93.0, 77.0, 77.0, 75.0, 83.0, 86.0, 89.0, 76.0, 88.0, 
 65.0, 65.0, 78.0, 77.0, 82.0, 97.0, 87.0, 83.0, 67.0, 83.0, 67.0, 77.0, 79.0, 
 79.0, 68.0, 69.0, 89.0, 79.0, 66.0, 85.0, 93.0, 74.0, 70.0, 83.0, 90.0, 75.0, 
 94.0, 77.0, 92.0, 84.0, 93.0, 83.0, 79.0, 87.0, 62.0, 85.0, 99.0, 76.0, 96.0, 
 89.0, 66.0, 85.0, 70.0, 83.0, 77.0, 96.0, 92.0, 76.0, 95.0, 84.0, 74.0, 83.0, 
 83.0, 89.0, 81.0, 91.0, 83.0, 74.0, 93.0, 73.0, 73.0, 84.0, 84.0, 83.0, 91.0, 
 68.0, 88.0, 72.0, 84.0, 93.0, 86.0, 83.0, 83.0, 77.0]
</code>

<h2>Exercise</h2>
Add 5 points to every score in the following list<br>
<code>
grades = [65.0, 78.0, 77.0, 82.0, 97.0, 87.0, 83.0, 67.0, 83.0, 67.0, 77.0, 79.0, 
 79.0, 68.0, 69.0, 89.0, 79.0, 66.0, 85.0, 93.0, 74.0, 70.0, 83.0, 90.0]
</code><br>
Calculate the mean and standard deviation before adding the 5 points.  Did the mean<br>
or the standard deviation change?  Use numpy arrays.<br>


In [79]:
import numpy as np
grades = [65.0, 78.0, 77.0, 82.0, 97.0, 87.0, 83.0, 67.0, 83.0, 67.0, 77.0, 79.0, 
 79.0, 68.0, 69.0, 89.0, 79.0, 66.0, 85.0, 93.0, 74.0, 70.0, 83.0, 90.0]
x = np.array(grades)
x_plus = np.array(grades)+5
print(x)
print(np.mean(x))
print(x_plus)
print(np.mean(x_plus))

[65. 78. 77. 82. 97. 87. 83. 67. 83. 67. 77. 79. 79. 68. 69. 89. 79. 66.
 85. 93. 74. 70. 83. 90.]
78.625
[ 70.  83.  82.  87. 102.  92.  88.  72.  88.  72.  82.  84.  84.  73.
  74.  94.  84.  71.  90.  98.  79.  75.  88.  95.]
83.625
