<h2>Exercise</h2>
The following list represents the diameters of circles:<br>
<code>
circle_diameters = [1,2,3,5,8,13,21]
</code><br>
1 - Calculate the area of each circle<br>
2 - Calculate the circumference of each circle<br>
<br>
Use Numpy for the solution

<h4>Solution</h4>

In [75]:
import numpy as np
import math
'''
Diameter: A line that passes through the center and its endpoints lie on the circle and represented by the letter 'd' or 'D'.

Radius: The distance from the center to a point on the boundary and represented by the letter 'r' or 'R'. 
 
Radius plays an important role in the formula for the area and circumference of a circle

Diameter formula: The diameter formula of a circle is twice its radius. Diameter = 2 × Radius
d = 2r or D = 2R
'''

# The diameter of the circle is known
circle_diameters = [1,2,3,5,8,13,21]
# The radius can be calculated as: r = d/2 or R = D/2 
d = np.array(circle_diameters)
r = d/2
print(r)
# Area of a circle is pi * r ^2
circle_area = math.pi * (r ** 2)
print('Areas '+'='*35)
print(circle_area)
# Circumference of a circle is 2 * pi * r
circle_circumference = (2 * math.pi) * r
print('Circumferences '+'='*35)
print(circle_circumference)

[ 0.5  1.   1.5  2.5  4.   6.5 10.5]
Areas ===================================
[  0.78539816   3.14159265   7.06858347  19.63495408  50.26548246
 132.73228961 346.36059006]
Circumferences ===================================
[ 3.14159265  6.28318531  9.42477796 15.70796327 25.13274123 40.8407045
 65.97344573]


<h2>Exercise</h2>
For each tuple in the list print the area of each rectangle<br><br>
Each element in the list represents the length and the width
<code>
dimensions = [(20,2),(2,3),(4,4),(6,6)]
</code><br>
Solve as a non numpy problem

<h4>Solution</h4>

In [76]:
dimensions = [(20,2),(2,3),(4,4),(6,6)]
area_rectanges = [(x[0]*x[1]) for x in dimensions]
print(area_rectanges)

[40, 6, 16, 36]


<h2>Exercise</h2>
The following dictionary represents the dimensions of an apartment in <br>
New York City.  <br><br>
<code>
apartment = {'Bedroom 1':(12,12), 'Bedroom 2': (12,10), 'Bathroom 1': (6,8),
    'Bathroom 2': (6,8), 'Kitchen': (10,8), 'Foyer': (14,4), 'Dining Room': (12,10),
    'Living Room': (12,15)}
</code><br>
1 - Calculate the square footage of each room<br>
2 - Calculate the total square footage of the apartment<br>
3 - If the apartment is selling for $90 a square foot.  How much is it selling for?<br><br>
NOTE: Selling price is the Square footage * price per square foot as 12<br>
Do not use numpy

In [77]:
apartment = {'Bedroom 1':(12,12), 'Bedroom 2': (12,10), 'Bathroom 1': (6,8),
    'Bathroom 2': (6,8), 'Kitchen': (10,8), 'Foyer': (14,4), 'Dining Room': (12,10),
    'Living Room': (15,22)}
print('Area '+'='*35)
square_footage = [f'{k} - Total area = {v[0]*v[1]}' for k,v in apartment.items()]
print(square_footage)

print('Total Square feet '+'='*35)
tot_sq_feet = sum([v[0]*v[1] for k,v in apartment.items()])
print(f'The total square feet of the apartment is {tot_sq_feet}')

print('Total Square feet '+'='*35)
tot_sq_feet = sum([v[0]*v[1] for k,v in apartment.items()])
print(f'The apartment will sell for {tot_sq_feet*12*90}')

Area ===================================
['Bedroom 1 - Total area = 144', 'Bedroom 2 - Total area = 120', 'Bathroom 1 - Total area = 48', 'Bathroom 2 - Total area = 48', 'Kitchen - Total area = 80', 'Foyer - Total area = 56', 'Dining Room - Total area = 120', 'Living Room - Total area = 330']
Total Square feet ===================================
The total square feet of the apartment is 946
Total Square feet ===================================
The apartment will sell for 1021680


<h2>Exercise</h2>
5 friends go out to dinner and their individual amounts were tallied on 1 bill<br>
<code>
dinner = [36, 42, 27, 32, 39]
</code><br>
Using numpy calculate the following:<br>
1 - The average meal price<br>
2 - The median meal price<br>
3 - The maximum cost for the meal<br>
4 - The least expensive meal<br>
5 - The difference each person varied from the mean<br>
6 - Add a 20% tip to each persons meal then Add 8.875 tax to the pre tax meal amount<br>
7 - What percentage of the total bill is each person contributing?<br>
8 - It was the birthday of the person who had the most expensive meal.  <br>
Distribute the cost of their meal amoungst the other patrons.<br>

<h4>Solution</h4>

In [78]:
dinner = [36, 42, 27, 32, 39]
print()

sort_dinner = np.sort(dinner)
print(sort_dinner)
print('==='*35)

total_dinner = np.sum(sort_dinner)
guests = np.size(sort_dinner)

# 1 - The average meal price
mean = np.mean(sort_dinner)

# 2 - The median meal price
median = np.median(sort_dinner)

# 3 - The maximum cost for the meal
max_meal = np.max(sort_dinner)

# 4 - The least expensive meal
min_meal = np.min(sort_dinner)

# 5 - The difference each person varied from the mean
differ = [(x-mean) for x in sort_dinner]

# 6 - Add a 20% tip to each persons meal then Add 8.875 tax to the pre tax meal amount
tip_and_tax = [round(((0.20 * x)+x)+(0.0875 * x),2) for x in sort_dinner]

# 7 - What percentage of the total bill is each person contributing?
percent = [ f'{x} is contributing {round(((x/np.sum(tip_and_tax))*100),2)}% of total meal cost' for x in tip_and_tax]

print(F'The {guests} friends Average costs = {mean} \n Median = {median}\n Most expensive meal = {max_meal} \n Least expensive meal = {min_meal}')
print('==='*35)
print(F'Difference from the mean = {differ} \n The tip and tax included = {tip_and_tax}')
print('==='*35)
print(percent)

# 8 - It was the birthday of the person with the most expensive meal. 
# Distribute the cost of their meal amongst the other patrons

Birthday = [ f'{round(x+((np.max(tip_and_tax))/4),2)} is {round(((x/np.sum(tip_and_tax))*100),2)+((np.max(tip_and_tax))/4)}% of the Birthday meal costs' for x in tip_and_tax if x != np.max(tip_and_tax)]
Birthday


[27 32 36 39 42]
The 5 friends Average costs = 35.2 
 Median = 36.0
 Most expensive meal = 42 
 Least expensive meal = 27
Difference from the mean = [-8.200000000000003, -3.200000000000003, 0.7999999999999972, 3.799999999999997, 6.799999999999997] 
 The tip and tax included = [34.76, 41.2, 46.35, 50.21, 54.08]
['34.76 is contributing 15.34% of total meal cost', '41.2 is contributing 18.18% of total meal cost', '46.35 is contributing 20.45% of total meal cost', '50.21 is contributing 22.16% of total meal cost', '54.08 is contributing 23.87% of total meal cost']


['48.28 is 28.86% of the Birthday meal costs',
 '54.72 is 31.7% of the Birthday meal costs',
 '59.87 is 33.97% of the Birthday meal costs',
 '63.73 is 35.68% of the Birthday meal costs']

<h2>Numpy continued</h2>

Strings can also be stored in a numpy array.<br>
<code>
import numpy as np
pasta_shapes = ['Macaroni','Rigatoni','Angel Hair','Spaghetti','Linguini']
shapes = np.array(pasta_shapes)
shapes = np.sort(shapes)
print(shapes)
print(shapes.dtype)
</code>

In [79]:
import numpy as np
pasta_shapes = ['Macaroni','Rigatoni','Angel Hair','Spaghetti','Linguini']
shapes = np.array(pasta_shapes)
shapes = np.sort(shapes)
print(shapes,shapes.dtype)


['Angel Hair' 'Linguini' 'Macaroni' 'Rigatoni' 'Spaghetti'] <U10


We can use short cut abreviations to assign the data types to numpy<br>
arrays:<br>
For i, u, f, S and U we can define size as well. <br>
We can combine each letter with a size as well like: 4,8<br>
<br>
<code>
import numpy as np
arr = np.array(list(range(1,11)), dtype='i8')
print(arr, arr.dtype)
</code>

<h2>Casting</h2>
We can convert python data type into numpy data type using 2 methods<br>
<br>
Method 1<br>
Use dtype parameter<br>
<br>
<code>
arr_string = np.array(list(range(1,11)), dtype='S')
print(arr_string)
</code><br>
Method 2<br>
Use astype()<br>
<code>
import numpy as np
arr = np.array(list(range(1,11)), dtype='i8')
arr_2 = arr.astype('S')
print(arr_2)
</code>

In [80]:
import numpy as np

arr_string = np.array(list(range(1,11)), dtype='S')
print(arr_string)

arr = np.array(list(range(1,11)), dtype='i8')
arr_2 = arr.astype('S')
print(arr_2)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10']
[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10']


<h2>Exercise</h2>
Take the following floating point number and cast them as integers<br>
Use both methods.<br>
<code>
rainfall = [2.3,3.7,2.4,1.9]
</code>

<h4>Solution</h4>

In [81]:
import numpy

rainfall = [2.3,3.7,2.4,1.9]
arr = np.array(rainfall, dtype = 'f')
print(arr, arr.dtype)

arr = np.float32(rainfall)
print(arr, arr.dtype)

[2.3 3.7 2.4 1.9] float32
[2.3 3.7 2.4 1.9] float32


In [82]:
import numpy as np
 
# converting to lowercase
print(np.char.lower(['Macaroni','Rigatoni','Angel Hair','Spaghetti','Linguini']))
 
# converting to lowercase
print(np.char.lower('PYTHON'))

# splitting a string
print(np.char.split('A journey of a million miles begins with one step'))
 
# splitting a string
print(np.char.split('tuples, lists, disctionaries', sep = ','))

['macaroni' 'rigatoni' 'angel hair' 'spaghetti' 'linguini']
python
['A', 'journey', 'of', 'a', 'million', 'miles', 'begins', 'with', 'one', 'step']
['tuples', ' lists', ' disctionaries']


In [83]:
import numpy as np
 
# splitting a string
print(np.char.join('-', 'pythonic'))
 
# splitting a string
print(np.char.join(['-', ':','|'], ['Data', 'science','fun']))  # multiple items to split

# Capitalize
print(np.char.title(['Data', 'science','fun']))

pasta_shapes = ['Macaroni','Rigatoni','Angel Hair','Spaghetti','Linguini']
new_shapes = np.array(pasta_shapes)
# counting a substring
print(np.char.count(new_shapes,'Spaghetti'))
 
# counting a substring
print(np.char.count(new_shapes, 'Linguini'))

# counting a substring
print(np.char.isnumeric('code'))
 
# counting a substring
print(np.char.isnumeric('12immersives'))

p-y-t-h-o-n-i-c
['D-a-t-a' 's:c:i:e:n:c:e' 'f|u|n']
['Data' 'Science' 'Fun']
[0 0 0 1 0]
[0 0 0 0 1]
False
False
