In [ ]:
import numpy as np

<h2>Introduction to Numpy</h2>
Numpy is a library for the Python programming language.  It brings the computational<br>
power of languages like C and Fortran to Python.  It includes support for large multi-dimensional<br>
arrays and matrices, along with a large collection of high-level mathematical functions to<br>
operate on these arrays.<br>

<h2>Creating Numpy Arrays</h2>
We can create a numpy array as follows:<br>
<code>
arr = np.array([1])
print(arr)
print(type(arr))
</code><br>
Here we create a one dimensional array better known as a point like<br>
on a number line<br>

In [ ]:
arr = np.array([1])
print(arr)
print(type(arr))

[1]
<class 'numpy.ndarray'>


Notice that the object is not a list but a new data structure.<br>
What will happen if we pass in an empty list to our Numpy array?<br>
<code>
arr = np.array([])
print(arr)
print(type(arr))
</code>
<br>
It will create an empty ndarray

In [ ]:
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


<h2>Adding a value to a ndarray</h2>
We can add values to a numpy array using the append command.<br>
However, we need to access a numpy method for append not a python one.<br>
Type the following:<br>
<code>
arr = np.array([])
np.append(arr,2)
print(arr)
</code><br>
When we execute our code we notice that the array arr is empty.  What happened?<br>
When we use the append it adds our changes to a copy of array.  We need to either<br>
overwite the variable we used in the original assignment or create a new variable name<br>

In [ ]:
arr = np.array([])
np.append(arr,2)
print(arr)
print(arr.dtype)

[]
float64


Type the following instead:<br>
<code>
arr = np.array([])
arr = np.append(arr,2)
print(arr)
</code>

In [ ]:
arr = np.array([])
arr = np.append(arr,2)
print(arr,arr.dtype)

[2.] float64


Now that we have added 1 value to our ndarray.  Let's examine its<br>
data type and its size.<br>
Type the following:<br>
<code>
arr = np.array([])
arr = np.append(arr,2)
print(arr)
print(arr.dtype)
print(arr.size)
</code><br>
When we appended the value to the ndarray we added what looked like an integer.<br>
The size returned a tople which represent the row size of 1 and no column dimension<br>
Let's look at the data types we can add after a brief exercise<br>

In [ ]:
arr = np.array([])
arr = np.append(arr,2)
print(arr)
print(arr.dtype)
print(arr.size)

[2.]
float64
1


<h2>Exercise</h2>
Create a numpy array , based on your limited knowlenge, of the number 1 through 10.<br>

In [ ]:
import numpy as np
arr = np.array(range(1,11))
print(arr)
print(arr.dtype)
print(arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
int64
10


<h2>Exercise</h2>
Creata numpy array with all odd numbers from 50 to 100

In [ ]:
arr2 = np.array([x for x in range(50,101) if x % 2 == 1])
print(arr2)

[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


<h2>Exercise</h2>
Create an ndarray with all prime numbers from 100 to 200

In [ ]:
import math
import numpy as np

def isPrime(num):
    prime = False
    if num > 1:
        prime = True
        for i in range(2,int(math.sqrt(num)+1)):
            if num % i == 0:
                prime = False
                break
    return prime

print(isPrime(31))

arr3 = np.array([x for x in range(100,201) if isPrime(x)])
print(arr3)

True
[101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191
 193 197 199]


<h2>Exercise</h2>
Create an ndarray with all powers of 2 from 1 to 10

In [ ]:
powersOf2 = np.array([2**x for x in range(1, 11)])
print(powersOf2)
print(powersOf2.size)
print(powersOf2.dtype)

[   2    4    8   16   32   64  128  256  512 1024]
10
int64


<h4>Numpy.arange()</h4>
There is a faster more effient way to create sequences in numpy through the use<br>
of the built in arange method.<br>
<code>
arr = np.arange(10)
print(arr)
</code>

In [ ]:
arr = np.arange(10)
print(arr)

arr = np.arange(1,11)
print(arr)

arr = np.arange(1,11,2)
print(arr)

arr = np.arange(1,11,2)
print(arr)
print(arr[1])    # Get the index 1 item

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[1 3 5 7 9]
3


<h2>Exercise</h2>
Create a numpy array that contains the even numbers from 10 to 40 that<br>
are not divisible by 5.

In [ ]:
evenNumbersNo5 = np.array([x for x in range(10,41) if x % 2 == 0 and x % 5 != 0])
print(evenNumbersNo5, evenNumbersNo5.size, evenNumbersNo5.dtype)

[12 14 16 18 22 24 26 28 32 34 36 38] 12 int64


<h2>Exercise</h2>
Write function to produce the Fibonacci sequence up to a length of 12<br>
seed = [0,1]<br>
<br>
def calc_fibo(seed,f_len = 5):<br>
    pass<br>

In [ ]:
def calc_fibo(seed, f_len = 5):
    while len(seed) < f_len:
        seed.append(seed[-1] + seed[-2])
    return seed
    
seed = [0, 1]
seq = calc_fibo(seed, 12)
print(f'The ratio is {seq[-1]/seq[-2]}')

The ratio is 1.6181818181818182


<h4>Lucas Sequence</h4>

In [ ]:
def calc_fibo(seed, f_len = 5):
    while len(seed) < f_len:
        seed.append(seed[-1] + seed[-2])
    return seed
    
seed = [2,1]
seq = calc_fibo(seed, 20)
print(f'The ratio is {seq[-1]/seq[-2]}')

The ratio is 1.6180339217722395


<h2>All sequences converge to the golden ratio</h2>

In [ ]:
def calc_fibo(seed, f_len = 5):
    while len(seed) < f_len:
        seed.append(seed[-1] + seed[-2])
    return seed
    
seed = [356,-57]
seq = calc_fibo(seed, 15)
print(f'The ratio is {seq[-1]/seq[-2]}')

The ratio is 1.6180659768843957


<h2>Numpy Data Types</h2>
We noted when we appended the value 2 to the empty array that it automatically<br>
converted it to a Float64 data type.  To cast a value we can do the following:<br>
Type:<br>
<code>
x = np.int_(1.0)
print(x,type(x))
</code><br>
or<br>
<code>
arr = np.array([2,3], dtype=np.int8)
print(arr)
print(arr.dtype)
print(arr)
</code>

In [ ]:
x = np.int_(1.0)
print(x,type(x))

arr = np.array([2,3], dtype=np.int8)
print(arr)
print(arr.dtype)
print(arr)

1 <class 'numpy.int64'>
[2 3]
int8
[2 3]


<h2>Data types can be used as functions</h2>
If you noticed above we cast the integer using this<br>
line:<br>
<code>
x = np.int_(1.0)
print(x,type(x))
print('='*32)

x = np.float32(range(30,50,3))
print(x,type(x))
print('='*32)

x = np.array([1, 2, 3], dtype='f')
print(x)
print(type(x))
</code>

In [ ]:
x = np.int_(1.0)
print(x,type(x))
print('='*32)

x = np.float32(range(30,50,3))
print(x,type(x))
print(x.dtype)
print('='*32)


x = np.array([1, 2, 3], dtype='f')
print(x)
print(type(x))
print(x.dtype)

1 <class 'numpy.int64'>
[30. 33. 36. 39. 42. 45. 48.] <class 'numpy.ndarray'>
float32
[1. 2. 3.]
<class 'numpy.ndarray'>
float32


<h4>Casting with astype()</h4>
We can convert all values in a numpy array with one function.<br>
Type:<br>
<code>
x = np.arange(11,40,5)
print(type(x))
print(x.dtype)
x = x.astype(np.int16)
print(x.dtype)
</code>
<br>
NOTE: Make sure you use the np.int8 or other type with the prefix

In [ ]:
x = np.arange(11,40,5)
print(x)
print(type(x))
print(x.dtype)
x = x.astype(np.int16)
print(x.dtype)

[11 16 21 26 31 36]
<class 'numpy.ndarray'>
int64
int16


We can add up the values in a numpy array<br>
<code>
x = np.arange(11,40,5)
print(np.sum(x))  # DO NOT TYPE x.sum()

x = [10, 5, 9, 22, -7, 3]
arr = np.array(x, dtype=np.int32)
print(arr)   
print(np.sort(arr)) # Sort the values

x = np.array([2,2,3,4], dtype=np.int32)
y = np.prod(x)      # multiply each value by itself
print(y)

x = [10, 5, 9, 22, -7, 3]
print(np.max(x))    # Get the max value

x = [10, 5, 9, 22, -7, 3]
print(np.mean(x))   # Get the mean

x = [10, 5, 9, 22, -7, 3]
print(np.min(x))    # Get the min
</code>  

In [ ]:
x = np.arange(11,40,5)
print(x)
print(np.sum(x))  # DO NOT TYPE x.sum()

x = [10, 5, 9, 22, -7, 3]
arr = np.array(x, dtype=np.int32)
print(arr)
print(np.sort(arr)) # Sort the values
# print(np.sort(arr)) # Sort the values


x = np.array([2,2,3,4], dtype=np.int32)
y = np.prod(x)      # multiply each value by itself
print(y)


x = [10, 5, 9, 22, -7, 3]
print(np.max(x))    # Get the max value


x = [10, 5, 9, 22, -7, 3]
print(np.mean(x))   # Get the mean


x = [10, 5, 9, 22, -7, 3]
print(np.min(x))    # Get the min

[11 16 21 26 31 36]
141
[10  5  9 22 -7  3]
[-7  3  5  9 10 22]
48
22
7.0
-7


<h2>Iterating over a numpy object</h2>
We can iterate over a numby object using the index of the object.<br>
<code>
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
for i in x:
    print(i, type(i))
</code>

In [ ]:
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
for i in x:
    print(i, type(i))

10 <class 'numpy.int16'>
5 <class 'numpy.int16'>
9 <class 'numpy.int16'>
22 <class 'numpy.int16'>
-7 <class 'numpy.int16'>
3 <class 'numpy.int16'>


We can use the index of the numpy object to change its values in the index.<br>
<code>
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
x[0] = x[0] * 2
print(x)
</code>

In [ ]:
x = [10, 5, 9, 22, -7, 3]
x = np.array(x, dtype=np.int16)
x[0] = x[0] * 2
print(x)

[20  5  9 22 -7  3]


<h1>Continued Fractions</h1>
Continued fractions are calculated by separating the integer portion of a number<br>
from its decimal portion.  For example Pi from the built in Python math library<br>
is equal to 3.141592653589793.  We would add the 3 to a python list and then take the <br>
decimal portion .141592653589793 and take the reciprical of it which is 7.062513305931057<br>
We would add the integer portion '7' to the list already created to make [3,7].  We would<br>
then repeat the process of taking the decimal portion and calculating its reciprical.<br>
For rational numbers the continued fration is finite wheeas all irrational numbers have <br>
infinite continued fractions.<br>
NOTE: Stop after a max of 25 iterations.

<h3>Exercise</h3>
Calculate the continued fractions of all numbers from square root of 2 through 50<br>
NOTE: Skip all perfect squares

In [ ]:
"""
step 1 - lets make sure our domain of numbers skip the perfect squares
Whose continued fractions are empty
"""
import math
numRange = range(2,50)
for num in numRange:
    if math.sqrt(num) - int(math.sqrt(num)) == 0:
        print('{0} is a perfect square and should be skipped'.format(num))

4 is a perfect square and should be skipped
9 is a perfect square and should be skipped
16 is a perfect square and should be skipped
25 is a perfect square and should be skipped
36 is a perfect square and should be skipped
49 is a perfect square and should be skipped


In [ ]:
"""
Step 2 - Create the reciprical fuction and the function to split
a number into the integer portion and the decimal portion
"""
import math

def reciprical(dec):
    return 1/float(dec) if float(dec) > 0 else 0

def splitNum(num):
    return str(num).split('.')

# Test each function
for i in range(1,11):
    print('The reciprical of {0} is {1}'.format(i,reciprical(i)))
    
# Lets now test the separation of the integer portion from the decimal
# portion for the following list
rationalNumbers = [2.12,5.005,7.9999]
for num in rationalNumbers:
    integerPortion,decimalPortion = splitNum(num)
    print('The number {0} caan be broken into integer: {1}, and decimal: .{2} '.format(num,
                                                                                      integerPortion,
                                                                                     decimalPortion))

The reciprical of 1 is 1.0
The reciprical of 2 is 0.5
The reciprical of 3 is 0.3333333333333333
The reciprical of 4 is 0.25
The reciprical of 5 is 0.2
The reciprical of 6 is 0.16666666666666666
The reciprical of 7 is 0.14285714285714285
The reciprical of 8 is 0.125
The reciprical of 9 is 0.1111111111111111
The reciprical of 10 is 0.1
The number 2.12 caan be broken into integer: 2, and decimal: .12 
The number 5.005 caan be broken into integer: 5, and decimal: .005 
The number 7.9999 caan be broken into integer: 7, and decimal: .9999 


In [ ]:
"""
Step 3 - Make sure that the algorithm either stops at 0 for the decimal portion
or 25 iterations
"""
import math

def reciprical(dec):
    return 1/float(dec) if float(dec) > 0 else 0

def splitNum(num):
    return str(num).split('.')

# continued fraction test
continuedFraction = []
num = 24/20
intPortion,decPortion = splitNum(num)
print('int - {0} - Dec - {1}'.format(intPortion,decPortion))
continuedFraction.append(int(intPortion))
tries = 0
while float('.'+decPortion ) > 0 and tries < 25:
    num = reciprical('.'+decPortion)
    print('The reciprical of {0} is {1}'.format('.'+decPortion,num))
    intPortion,decPortion = splitNum(num)
    print('int - {0} - Dec - {1}'.format(intPortion,decPortion))
    continuedFraction.append(int(intPortion))
    tries += 1
print(continuedFraction)

int - 1 - Dec - 2
The reciprical of .2 is 5.0
int - 5 - Dec - 0
[1, 5]


In [ ]:
"""
Step 4 - run for the complete set of numbers excluding the perfect squares
"""
import math

def reciprical(dec):
    return 1/float(dec) if float(dec) > 0 else 0

def splitNum(num):
    return str(num).split('.')

numRange = range(2,50)
for num in numRange:
    if math.sqrt(num) - int(math.sqrt(num)) == 0:
        pass
    else:
        continuedFraction = []
        origNum = num
        num =  math.sqrt(num)
        intPortion,decPortion = splitNum(num)
        continuedFraction.append(int(intPortion))
        tries = 0
        while float('.'+decPortion ) > 0 and tries < 25:
            num = reciprical('.'+decPortion)
            intPortion,decPortion = splitNum(num)
            continuedFraction.append(int(intPortion))
            tries += 1
        print('The continued fraction for sqrt({0}) is {1}'.format(origNum,continuedFraction))

The continued fraction for sqrt(2) is [1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2]
The continued fraction for sqrt(3) is [1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1]
The continued fraction for sqrt(5) is [2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 2, 2, 9, 3, 12, 2, 2, 1, 2, 2, 1]
The continued fraction for sqrt(6) is [2, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 3, 1, 9, 1, 1, 17, 10, 3, 1, 16]
The continued fraction for sqrt(7) is [2, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 4, 1]
The continued fraction for sqrt(8) is [2, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 3, 1, 1, 1, 6]
The continued fraction for sqrt(10) is [3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 2, 2, 4, 1, 4, 3, 1, 3, 1, 6, 2, 3, 3, 3, 7]
The continued fraction for sqrt(11) is [3, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 1, 8, 2, 2, 27, 5, 3, 6, 1, 1, 6, 4, 3]
The continued fraction for sqrt(12) is [3, 2, 6, 2, 6, 2,

<h2>Exercise</h2>
Add 5 points to every score in the following list<br>
<code>
grades = [65.0, 78.0, 77.0, 82.0, 97.0, 87.0, 83.0, 67.0, 83.0, 67.0, 77.0, 79.0, 
 79.0, 68.0, 69.0, 89.0, 79.0, 66.0, 85.0, 93.0, 74.0, 70.0, 83.0, 90.0]
</code><br>
Calculate the mean and standard deviation before adding the 5 points.  Did the mean<br>
or the standard deviation change?  Use numpy arrays.<br>

In [ ]:
import numpy as np
grades = [65.0, 78.0, 77.0, 82.0, 97.0, 87.0, 83.0, 67.0, 83.0, 67.0, 77.0, 79.0, 
 79.0, 68.0, 69.0, 89.0, 79.0, 66.0, 85.0, 93.0, 74.0, 70.0, 83.0, 90.0]
x = np.array(grades)
print(x)
print(np.std(x))
print(np.mean(x))
x_plus = np.array(grades)+5
print(x_plus)
print(np.std(x_plus))
print(np.mean(x_plus))

[65. 78. 77. 82. 97. 87. 83. 67. 83. 67. 77. 79. 79. 68. 69. 89. 79. 66.
 85. 93. 74. 70. 83. 90.]
8.85914075968996
78.625
[ 70.  83.  82.  87. 102.  92.  88.  72.  88.  72.  82.  84.  84.  73.
  74.  94.  84.  71.  90.  98.  79.  75.  88.  95.]
8.85914075968996
83.625


<h2>Numpy continued</h2>
We will explore Numpy ufuncs, which stand for 'Universal Functions', that<br>
operate on the ndarray object.<br>
ufuncs are used to implement vectorization in NumPy which is way faster than <br>
iterating over elements.<br>
<br>
They also provide broadcasting and additional methods like reduce, accumulate etc. <br>
that are very helpful for computation.<br>
<br>
ufuncs also take additional arguments, <br>
like:<br>

- where - boolean array or condition defining where the operations should take place.<br>
- dtype - defining the return type of elements.<br>
- out - output array where the return value should be copied.<br>

<h4>Adding 2 python lists together</h4>
<br>
<code>
x = [3, 5, 7, 9]
y = [4, 6, 8, 10]
z = np.add(x, y)

print(z)  
print(type(z))
</code>
<br>
NOTE: The shape of the numpy objects must be the same.

In [ ]:
import numpy as np
x = [3, 5, 7, 9]
y = [4, 6, 8, 10]
z = np.add(x, y)

print(z,type(z)) 

[ 7 11 15 19] <class 'numpy.ndarray'>


<h4>Subtraction</h4>
<br>
<code>
x = [13, 25, -7, 39]
y = [4, 6, 8, 10]
z = np.subtract(x, y)

print(z)
print(type(z))
</code>

In [ ]:
x = [13, 25, -7, 39]
y = [4, 6, 8, 10]
z = np.subtract(x, y)

print(z,type(z))

[  9  19 -15  29] <class 'numpy.ndarray'>


<h4>Multiplication</h4>
<code>
x = [13, 25, -7, 39]
y = [4, 6, 8, 10]
z = np.multiply(x, y)

print(z)
print(type(z))
</code>

In [ ]:
x = [13, 25, -7, 39]
y = [4, 6, 8, 10]
z = np.multiply(x, y)

print(z,type(z))

[ 52 150 -56 390] <class 'numpy.ndarray'>


<h4>Division</h4>
<code>
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 8, 13, 21, 34])

newarr = np.divide(arr1, arr2)
print(newarr) 
</code>
<br>
Powers
<code>
arr1 = np.array([2, 3, 4, 5, 6, 7])
arr2 = np.array([7, 6, 5, 4, 3, 2])

newarr = np.power(arr1, arr2)
print(newarr) 
</code>
<br>
Reminder/ Modulus
<code>
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 6, 14, 8, 13])
newarr = np.remainder(arr1, arr2)

print(newarr) 


arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr) 
</code>
<br>
Quotient and Mod
<code>
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 9, 8, 13, 43])
newarr = np.divmod(arr1, arr2)   # Returns 2 arrays !!!

print(newarr) 
</code>
<br>
Absolute Value
<code>
arr = np.array([-1, -2, 10, 2, 13, -9])
newarr = np.absolute(arr)

print(newarr) 
</code>

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 8, 13, 21, 34])

newarr = np.divide(arr1, arr2)
print(newarr) 

arr1 = np.array([2, 3, 4, 5, 6, 7])
arr2 = np.array([7, 6, 5, 4, 3, 2])

newarr = np.power(arr1, arr2)
print(newarr) 

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 6, 14, 8, 13])
newarr = np.remainder(arr1, arr2)

print(newarr) 

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr) 
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 9, 8, 13, 43])
newarr = np.divmod(arr1, arr2)

print(newarr) 
arr = np.array([-1, -2, 10, 2, 13, -9])
newarr = np.absolute(arr)

print(newarr) 

[3.33333333 4.         3.75       3.07692308 2.38095238 1.76470588]
[ 128  729 1024  625  216   49]
[ 1  6  0 12  2  8]
[ 1  6  3  0  0 27]
(array([5, 4, 3, 5, 3, 1]), array([ 0,  0,  3,  0, 11, 17]))
[ 1  2 10  2 13  9]


<h2>Numpy ufunc - Rounding Decimals</h2><br>
There are primarily five ways of rounding off decimals in NumPy:<br>
- truncation - remove the decimal portion of a number
<br>
<code>
import numpy as np
arr = np.trunc([-3.1666, 3.6667, 111.23334])
print(arr)    
</code><br>
- rounding - equivalent to python rounding
<br>
<code>
arr = np.around(3.1417, 2)
print(arr)     
</code><br>
- floor - Returns the next lower integer number
<br>
<code>
arr = np.floor([-3.1666, 3.6667])
print(arr)     
</code><br>
- ceil - Returns the next higher integer number
<br>
<code>
arr = np.ceil([-3.1666, 3.6667])
print(arr)     
</code><br>

In [ ]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667, 111.23334])
print(arr) 

arr = np.around(3.1417, 2)
print(arr) 

arr = np.floor([-3.1666, 3.6667])
print(arr) 

arr = np.ceil([-3.1666, 3.6667])
print(arr) 

[ -3.   3. 111.]
3.14
[-4.  3.]
[-3.  4.]


<h2>Summing all elements</h2>
We can use the Numpy sum function to add up all of the values in<br>
1 or more np.arrays<br>
<code>
import numpy as np

arr1 = np.array([3, 4, 1])
arr2 = np.array([-1,-2, 7])
newarr = np.sum([arr1, arr2])
print(newarr) 
</code>

In [ ]:
import numpy as np

arr1 = np.array([3, 4, 1])
arr2 = np.array([-1,-2, 7])
newarr = np.sum([arr1, arr2])
print(newarr) 

12


<h1>Exercise</h1>

In [ ]:
x = [1,2,0,5,1,4,-1,2]

def greatNumber(lst):
    theMax = lst[0]
    for num in lst:
        if theMax < num:
            theMax = num
    return theMax
  
res = greatNumber(x)
print(res)


5


<h2>Exercise</h2>
You have the following data structure:<br>
<code>
processes = [{'command':'docker build -t python101:1.0'},
             'Reboot server',
             'Data cleaning',
             {'command': 'git stash','server':'mid west'}]
</code><br>
How do you execute the process that contains the command - 'git stash' first?<br>

In [ ]:
# step 1 to iterate and examine the data type
processes = [{'command':'docker build -t python101:1.0'},
             'Reboot server',
             'Data cleaning',
             {'command': 'git stash','server':'mid west'}]
for process in processes:
    print(process,type(process))

{'command': 'docker build -t python101:1.0'} <class 'dict'>
Reboot server <class 'str'>
Data cleaning <class 'str'>
{'command': 'git stash', 'server': 'mid west'} <class 'dict'>


In [ ]:
# step 2 - Use list comp and isinstance to change the order
processes = [{'command':'docker build -t python101:1.0'},
             'Reboot server',
             'Data cleaning',
             {'command': 'git stash','server':'mid west'}]

newOrder = [x for x in processes if isinstance(x,dict) and x["command"] == 'git stash'] + \
    [x for x in processes if not (isinstance(x,dict) and x["command"] == 'git stash')]
print(newOrder)

[{'command': 'git stash', 'server': 'mid west'}, {'command': 'docker build -t python101:1.0'}, 'Reboot server', 'Data cleaning']
